### ISSUE TITLE
ios版本设置太高了！

### ISSUE THREAD

**Issue by sujianchao** [chai2010/ptyy#6]
此 应用软件 需要ios9.3 或更高版本~~
建议尽可能的降到ios5或6或7版本才好。

**Comment by chai2010** [comment]
en, 目前是基于免费版的 RubyMotion，要求最新的9.3版本。
我也是iOS新手，怎么解决这个问题需要先想下。

抱歉

**Comment by chai2010** [comment]
@sujianchao 已经上架的1.2改用swift重现实现，支持IOS7。

如果没有问题的话，稍后就关闭这个问题了

**Comment by sujianchao** [comment]
@chai2010 1.2版已下载，谢谢你的努力和分享！
